---
title: "DATA 605 - Homework 1"
author: "Manolis Manoli"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r loading-libraries, echo=TRUE, results='hide', warning=FALSE, message=FALSE}
library(ggplot2)
library(psych)
library(dplyr)
library(knitr)
library(tidyr)
```

## Problem Set 1

```{r dot-product, eval=TRUE}
u = c(.5,.5)
v = c(3,-4)
dotuv = u[1] * v[1] + u[2] * v [2]
dotuv
```

```{r dot-product-function, eval=TRUE}
dotprod <- function(u,v) {
  if (length(u) != length(v)) {
    result = 'Error: vectors are of different length'
  }
  else {
    sumdotprod = 0
    for(i in c(1:length(u))){
      sumdotprod = sumdotprod + (u[i] * v[i])
    }
    result = sumdotprod
  }
return(result)
  }
```

```{r dot-product-call, eval=TRUE}
dotprod(u,v)
```

The length is the square root of the dot product with itself.
We can therefore call the function above with the same argument for both vectors and square root the result:

```{r vector-length, eval=TRUE}
len_u = sqrt(dotprod(u,u))
len_v = sqrt(dotprod(v,v))

len_u
len_v
```

The linear combination is:

```{r vector-lin, eval=TRUE}
3*u-2*v
```

and the angle between the two vectors is (in degrees):

```{r vector-angle, eval=TRUE}
acos(dotprod(u,v)/(len_u * len_v))*180/pi
```

## Problem Set 2

```{r Gauss-Jordan-function, eval=TRUE}

GaussJordan <- function(A,b) {

  c12 = A[2,1]/A[1,1]
  A[2,] = A[2,]-A[1,]*c12
  b[2]=b[2]-b[1]*c12
  
  c13 = A[3,1]/A[1,1]
  A[3,] = A[3,]-A[1,]*c13
  b[3] = b[3]-b[1]*c13
  
  c23 = A[3,2]/A[2,2]
  A[3,] = A[3,]-A[2,]*c23
  b[3] = b[3]-b[2]*c23
  
  c3=A[3,3]
  A[3,] = A[3,]/c3
  b[3] = b[3]/c3
  
  c23 = A[2,3]
  A[2,] = A[2,]-A[3,]*c23
  b[2] = b[2]-b[3]*c23
  
  c22 = A[2,2]
  A[2,] = A[2,]/c22
  b[2] = b[2]/c22
  
  c13 = A[1,3]
  A[1,] = A[1,]-A[3,]*c13
  b[1] = b[1]-b[3]*c13
  
  c22 = A[2,2]
  A[1,] = A[1,]-A[2,]*c22
  b[1] = b[1]-b[2]*c22 
  
  return(b)
 
}

```

Testing with the given system:

```{r Gauss-Jordan-applied, eval=TRUE}

A = matrix(c(1,1,3,2,-1,5,-1,-2,4),nrow=3,ncol=3,byrow = T)
b = c(1,2,6)

round(GaussJordan(A,b),2)
```
   
Github (both PDF and RMarkdown):

https://github.com/chilleundso/Data605_CompMath/tree/master/Homework1
    

